// <auto-generated />
using BlazorMaze;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorMaze.Migrations
{
    [DbContext(typeof(MazeContext))]
    partial class MazeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("BlazorMaze.MazeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GridString")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpaceColorString")
                        .HasColumnType("TEXT");

                    b.Property<string>("WallColorString")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MazeModels");
                });
#pragma warning restore 612, 618
        }
    }
}
